name: ArantoServerBackend

on:
  push:
    branches: [ "main" ]

jobs:
  postgres:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: aranto
          POSTGRES_PASSWORD: 1234
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Verify PostgreSQL connection
        run: |
          psql -h postgres -d aranto -U postgres -c 'SELECT 1;'
        env:
          PGPASSWORD: 1234
      - name: Create test database
        run: psql -c 'CREATE DATABASE ${DB_NAME};' -U ${DB_USER} -h ${DB_HOST}
        env:
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_HOST: postgres
          DB_NAME: aranto_test

      - name: Fresh database setup
        run: |
            npx sequelize-cli db:migrate:undo:all --env test
            npx sequelize-cli db:migrate --env test
            npx sequelize-cli db:seed:all --env test
        env:
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_HOST: postgres
          DB_TEST_NAME: aranto_test
        
        

      - name: Install Node.js dependencies
        run: npm install
     
      - name: Run Synchronization Script
        run: node index.js
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: postgres
          DB_NAME: ${{ secrets.DB_NAME }}
      - name: Run Migrations
        run: npx sequelize-cli db:migrate
        env:
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_HOST: postgres
          DB_NAME: aranto

      - name: Run Seeders
        run: npx sequelize-cli db:seed:all
        env:
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_HOST: postgres
          DB_NAME: aranto

      - name: Run Tests
        run: npm test
        env:
          DB_USER: postgres
          DB_PASSWORD: 1234
          DB_HOST: postgres
          DB_NAME: aranto
