name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: aranto
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - run: npm test

    - name: Run Synchronization Script
      run: node sync.js
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_NAME: aranto

    - name: Run Migrations
      run: npx sequelize-cli db:migrate
      env:
        DB_USER: myuser
        DB_PASSWORD: mypassword
        DB_HOST: localhost
        DB_NAME: aranto

    - name: Run Seeders
      run: npx sequelize-cli db:seed:all
      env:
        DB_USER: myuser
        DB_PASSWORD: mypassword
        DB_HOST: localhost
        DB_NAME: aranto

    - name: Deploy to Server
      env:
        TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: ssh user@server "cd /path/to/app && git pull && npm install && npm run build"
